trigger:
- main

pool:
  vmImage: windows-latest

variables:
    buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'


  
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/src/DeveloperPath.WebApi/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/tests/*/*.csproj'
    arguments: '-- configuration ($buildConfiguration)'
- task: Bash@3
  displayName: 'Build info json'
  inputs:
    targetType: 'inline'
    script: 'echo -e -n "{\"buildNumber\":\"$(Build.BuildNumber)\",\"buildId\":\"$(Build.BuildId)\",\"branchName\":\"$(Build.SourceBranchName)\",\"commitHash\":\"$(Build.SourceVersion)\"}" > "**/src/DeveloperPath.WebApi/buildinfo.json"'
- task: DotNetCoreCLI@2 
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/src/DeveloperPath.WebApi/DeveloperPath.WebApi.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'