trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  project: '**/*.sln'
  dotNetVersion: '6.0.x'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
- task: DotNetCoreCLI@2 
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/src/AzureFunctions/DeveloperPath.EmailVerificationFn/DeveloperPath.EmailVerificationFn.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'